'use strict';
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'America/New_York'});
  const base='https://kscot101.github.io/Gridiron-Pulse/';
  await context.route(base+'**',async route=>{
    const url=new URL(route.request().url());
    const rel=decodeURIComponent(url.pathname.slice('/Gridiron-Pulse/'.length))||'index.html';
    const local=path.resolve(rel);
    if(!local.startsWith(process.cwd()+path.sep)||!fs.existsSync(local)||!fs.statSync(local).isFile()) return route.fulfill({status:404,body:'Not found'});
    return route.fulfill({path:local});
  });
  const page=await context.newPage(), errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const report={testedAt:new Date().toISOString(),mode:'staged files at production origin; saved ledger and existing player-stats module'};
  try{
    await page.goto(base+'pick-tracker.html',{waitUntil:'domcontentloaded'});
    await page.waitForFunction(()=>window.GPPickTracker?.data,null,{timeout:45000});
    const d=JSON.parse(fs.readFileSync('data/projection-trial.json','utf8'));
    const key=r=>r.season+'|'+r.gameId+'|'+r.athleteId;
    const expected=new Set(d.forecasts.map(key)).size;
    assert.equal(await page.locator('.pt-pick').count(),expected);
    report.individualPicks=expected;
    report.byPosition=await page.evaluate(()=>Object.fromEntries(['QB','RB','WR','TE'].map(p=>[p,document.querySelectorAll('.pt-pick[data-position="'+p+'"]').length])));
    assert.equal(await page.locator('.pt-position-group').count(),Object.values(report.byPosition).filter(Boolean).length);
    await page.screenshot({path:'pick-tracker-desktop.png'});
    await page.locator('[data-pt-position="WR"]').click();
    assert.equal(await page.locator('.pt-pick:not([data-position="WR"])').count(),0);
    await page.locator('[data-pt-position="all"]').click();
    const row=d.forecasts.find(r=>r.model==='workload-trial-1'&&r.predictions.passing_yards!=null)||d.forecasts[0];
    const metric=Object.keys(row.predictions)[0];
    await page.locator('#pt-search').fill(row.playerName);
    const selected=page.locator('[data-pick-key="'+key(row)+'"]');
    await selected.locator('.pt-detail summary').click();
    const value=await selected.locator('[data-stat="'+metric+'"] [data-model="'+row.model+'"]').innerText();
    assert.equal(Number(value.replace(/,/g,'')),row.predictions[metric]);
    report.canonicalValues=true;
    await selected.locator('.pt-follow').click();
    await page.reload({waitUntil:'domcontentloaded'});
    await page.waitForFunction(()=>window.GPPickTracker?.data,null,{timeout:45000});
    await page.locator('#pt-favorites').check();
    const savedGames=new Set(d.forecasts.filter(r=>r.athleteId===row.athleteId).map(key)).size;
    assert.equal(await page.locator('.pt-pick').count(),savedGames);
    assert.ok((await page.locator('.pt-pick h3').allTextContents()).every(t=>t===row.playerName));
    await page.locator('.pt-pick .gp-player-name').first().click();
    await page.getByRole('dialog').waitFor({state:'visible',timeout:10000});
    await page.keyboard.press('Escape');
    report.playerPopup=true;
    report.sharedFollowPersists=true;
    await page.locator('.pt-reset').click();
    await page.locator('#pt-status').selectOption('graded');
    if(!Object.keys(d.outcomes).length)assert.equal(await page.locator('.pt-pick').count(),0);
    await page.locator('.pt-reset').click();
    await page.locator('#pt-search').fill('nobodymatchesthis');
    assert.equal(await page.locator('.pt-pick').count(),0);
    await page.locator('.pt-reset').click();
    await page.locator('#pt-week').selectOption(row.season+'|'+row.week);
    await page.locator('#pt-team').selectOption(row.team);
    assert.ok(await page.locator('.pt-pick').count()>0);
    assert.ok((await page.locator('.pt-player small').allTextContents()).every(t=>t.startsWith(row.team+' /')));
    await page.locator('.pt-reset').click();
    report.positionSearchWeekTeamStatusFilters=true;
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:'pick-tracker-mobile.png'});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);
    await page.locator('.pt-detail summary').first().click();
    await page.locator('.pt-pick').first().scrollIntoViewIfNeeded();
    await page.screenshot({path:'pick-tracker-mobile-details.png'});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);
    await page.setViewportSize({width:320,height:740});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);
    report.mobileOverflow=false;
    await page.goto(base+'projection-trial.html',{waitUntil:'domcontentloaded'});
    assert.equal(await page.locator('#gp-pick-tracker-link').getAttribute('href'),'pick-tracker.html');
    assert.ok(fs.readFileSync('index.html','utf8').includes('id="gp-pick-tracker-link"'));
    report.homeAndLabLinks=true;
    report.pageErrors=errors;assert.deepEqual(errors,[]);
    report.passed=true;
    fs.writeFileSync('data/pick-tracker-verification.json',JSON.stringify(report,null,2));
    console.log(JSON.stringify(report,null,2));
  }catch(e){report.error=e.message;report.pageErrors=errors;fs.writeFileSync('pick-tracker-browser-error.json',JSON.stringify(report,null,2));await page.screenshot({path:'pick-tracker-error.png'}).catch(()=>{});throw e;}
  finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
