'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const T = require('../assets/pick-tracker.js');
const now = Date.parse('2026-09-24T20:00:00Z');
const base = {id:'g1|p1|workload-trial-1',season:2026,week:3,gameId:'g1',athleteId:'p1',playerName:'Example Receiver',position:'WR',team:'KC',opponent:'MIA',recordedAt:'2026-09-24T19:00:00Z',kickoff:'2026-09-25T00:15:00Z',model:'workload-trial-1',predictions:{receiving_yards:55,receiving_tds:0.5},forecastHash:'test-fixture-only'};
const data = {forecasts:[base],outcomes:{}};
assert.equal(T.groupsFrom(data,{},now)[0].status,'pending');
assert.equal(T.groupsFrom(data,{g1:{state:'in'}},now)[0].status,'live');
assert.equal(T.groupsFrom(data,{},now+86400000)[0].status,'awaiting');
const final={status:'FINAL',metrics:{receiving_yards:{prediction:55,actual:70,error:15,absoluteError:15,status:'GRADED'},receiving_tds:{prediction:0.5,actual:0,error:-0.5,absoluteError:0.5,status:'GRADED'}}};
data.outcomes[base.id]=final;
let g=T.groupsFrom(data,{},now)[0];
assert.equal(g.status,'graded');
assert.equal(T.actualFor(g,'receiving_tds',data.outcomes).value,0);
assert.equal(T.metricGrade(base,'receiving_yards',data.outcomes).absoluteError,15);
final.metrics.receiving_tds={status:'NO_DATA',prediction:0.5,actual:null};
assert.equal(T.groupsFrom(data,{},now)[0].status,'partial');
final.metrics.receiving_yards={status:'NO_DATA',prediction:55,actual:null};
assert.equal(T.groupsFrom(data,{},now)[0].status,'no-data');
data.outcomes[base.id]={status:'INVALID_CAPTURE'};
assert.equal(T.groupsFrom(data,{},now)[0].status,'excluded');
assert.equal(T.actualFor(T.groupsFrom(data,{},now)[0],'receiving_yards',data.outcomes).value,null);
const later={...base,id:'g2|p1|workload-trial-1',gameId:'g2',week:4};
assert.equal(T.groupsFrom({forecasts:[base,later],outcomes:{}},{},now).length,2);
const baseline={...base,id:'g1|p1|v2.1-tracked-1',model:'v2.1-tracked-1'};
assert.equal(T.groupsFrom({forecasts:[base,baseline],outcomes:{}},{},now).length,1);
assert.throws(()=>T.groupsFrom({forecasts:[base,base],outcomes:{}},{},now),/Duplicate/);
assert.throws(()=>T.groupsFrom({forecasts:[base,{...baseline,position:'TE'}],outcomes:{}},{},now),/Conflicting/);
const conflict={forecasts:[base,baseline],outcomes:{[base.id]:{status:'FINAL',metrics:{receiving_yards:{prediction:55,actual:70,absoluteError:15,status:'GRADED'}}},[baseline.id]:{status:'FINAL',metrics:{receiving_yards:{prediction:55,actual:71,absoluteError:16,status:'GRADED'}}}}};
assert.equal(T.groupsFrom(conflict,{},now)[0].status,'conflict');
for(const x of [null,undefined,' ',true,[],{},'invalid']) assert.equal(T.number(x),null);
assert.equal(T.number(0),0);
assert.equal(T.number(-2),-2);
assert.equal(T.number('12.2'),12.2);
const old={ok:true,fetchedAt:'2026-09-23T00:00:00Z',scoreboard:{events:[{id:'g1',status:{type:{state:'in'}}}]}};
assert.deepEqual(T.gamesFrom(old,null,now),{});
const real=JSON.parse(fs.readFileSync('data/projection-trial.json','utf8'));
const before=JSON.stringify(real);
const groups=T.groupsFrom(real,{},now);
const expected=new Set(real.forecasts.map(r=>`${r.season}|${r.gameId}|${r.athleteId}`)).size;
assert.equal(groups.length,expected);
assert.equal(before,JSON.stringify(real));
const f={position:'WR',query:'',week:'all',team:'all',status:'all',favorites:false};
assert.ok(T.filtered(groups,f,()=>false).every(g=>g.position==='WR'));
assert.equal(T.filtered(groups,{...f,position:'all',query:'Mahomes'},()=>false).length,1);
const n=T.counts(groups);assert.equal(n.total,n.graded+n.awaiting+n.review);
console.log('PASS: individual identity, repeated weeks, model pairing, all result states, exact errors, zero vs missing, stale-score exclusion, filters, no ledger mutation. '+groups.length+' saved player-game picks.');
