'use strict';
const assert=require('node:assert/strict');
const F=require('../assets/homepage-feed.js');
const now=Date.parse('2026-09-24T16:30:00Z');
const e={id:'current-game',date:'2026-09-25T00:15:00Z',name:'Current matchup',week:{number:3},status:{type:{state:'pre',completed:false}},competitions:[{competitors:[{homeAway:'away',team:{id:'1',abbreviation:'A'}},{homeAway:'home',team:{id:'2',abbreviation:'B'}}]}]};
const board={season:{year:2026,type:2},week:{number:3},events:[e]};
const old={generatedAt:'2026-09-15T19:38:59Z',season:{year:2026,type:2,week:1},games:[{id:'old-game',date:'2026-09-15T00:15:00Z',status:{state:'post',completed:true}}],playerEdge:[{gameId:'old-game',picks:[{name:'Historical pick'}]}],results:[{gameId:'old-game',player:'Historical pick',team:'A',outcome:'NO DATA'}],modelPerformance:{overall:{graded:1}}};
const out=F.compose(board,[old],null,null,now);
assert.equal(out.season.week,3);
assert.equal(out.games.length,1);
assert.equal(out.feedStatus.analysisCurrent,false);
assert.equal(out.playerEdge.length,0);
assert.equal(out.availability.items.length,0);
assert.equal(out.results.length,1);
assert.equal(out.results[0].gameDate,old.games[0].date);
assert.equal(out.feedStatus.analysisGeneratedAt,old.generatedAt);
assert.equal(F.current(old,board,now),false);
const renewed={...out,generatedAt:new Date(now).toISOString(),playerEdge:[{gameId:e.id,picks:[{name:'Current pick',score:10}]}]};
assert.equal(F.current(renewed,board,now),true);
assert.equal(F.current({...renewed,season:{...renewed.season,week:1}},board,now),false);
assert.equal(F.compose(board,[renewed,old],null,null,now).playerEdge.length,1);
assert.equal(F.number(0),0);
for(const val of [null,undefined,' ','bad',true,[],{}])assert.equal(F.number(val),null);
assert.equal(F.pickSpotlight(out.games,null,now).id,e.id);
assert.equal(F.pickSpotlight(old.games,null,now),null);
assert.equal(F.compose(null,[old],null,null,now).games.length,0);
console.log('PASS: stale feed rejected; current week retained; outcomes archived; missing values distinct from zero; fresh analysis accepted; expired spotlight blocked.');
